version: "2"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - "3000:3000"
